Hopper
FRC125/FRamework-examples pull request #9
Opened 2017-02-05 20:13 UTC by AndreasLc1103

Added Ball Hopper Subsystem

2017-02-06 23:33 UTC, laposata12 commented on src/com/nutrons/steamworks/Hopper.java
> +        this.runHopper = Flowable.just(new RunAtPowerEvent(0.9));
the 0.9 should be a variable rather than a constant

2017-02-07 00:12 UTC, kreeve submitted a review, later dismissed

2017-02-07 00:12 UTC, kreeve commented on src/com/nutrons/steamworks/Hopper.java
> +=======
Get rid of merge conflicts!

2017-02-07 00:42 UTC, MiloDavis requested changes

2017-02-07 00:42 UTC, MiloDavis commented on src/com/nutrons/steamworks/RobotMap.java
> +    public static final int TOP_HOPPER_MOTOR = 0; // need to change ln 10 and 11 when we get actual port #
Make into TODO

2017-02-07 00:42 UTC, MiloDavis commented on src/com/nutrons/steamworks/Hopper.java
> +     * HopperController
Make into real [javadoc](http://www.drjava.org/docs/user/ch10.html)

2017-02-07 00:42 UTC, MiloDavis commented on src/com/nutrons/steamworks/Hopper.java
> +    private final Consumer<ControllerEvent> hopperController;
Comment about this being a leader and follower

2017-02-07 01:33 UTC, MiloDavis commented on src/com/nutrons/steamworks/Hopper.java
> +     * HopperController
This is a constant, mark it as such make `final`

2017-02-07 01:36 UTC, MiloDavis requested changes

2017-02-07 01:36 UTC, MiloDavis commented on src/com/nutrons/steamworks/RobotBootstrapper.java
> +    private Talon TopHopperMotor;
Lowercase variable names

2017-02-07 23:10 UTC, MiloDavis requested changes

2017-02-07 23:10 UTC, MiloDavis commented on src/com/nutrons/steamworks/Hopper.java
> +    private final static double spinsPower = 0.9;
Constant notation `SPIN_POWER`

2017-02-07 23:10 UTC, MiloDavis commented on src/com/nutrons/steamworks/RobotMap.java
> +    // @TODO Change Assign hopper ports when given robot
`// TODO: Change hopper ports to match robot`

2017-02-07 23:21 UTC, MiloDavis approved these changes

2017-02-07 23:22 UTC, merged